apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-blue
  namespace: blue-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-bg
      version: blue
  template:
    metadata:
      labels:
        app: nginx-bg
        version: blue
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.1
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 50Mi
            cpu: 10m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-green
  namespace: blue-green
spec:
  replicas: 0
  selector:
    matchLabels:
      app: nginx-bg
      version: green
  template:
    metadata:
      labels:
        app: nginx-bg
        version: green
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.2
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 50Mi
            cpu: 10m
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-bg-active
  namespace: blue-green
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx-bg
    version: blue
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-bg-preview
  namespace: blue-green
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx-bg
    version: green 