apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 15.0.2
    chart: nginx
    helm:
      parameters:
      - name: replicaCount
        value: "5"
      - name: service.type
        value: ClusterIP
      - name: image.tag
        value: "1.25.2-debian-11-r0"
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground 